[WIP] BugFix | #1604 | Duplicate extension key prefix
zephir-lang/zephir pull request #1809
Opened 2019-02-18 20:19 UTC by AlexNDRmac

2019-02-18 20:25 UTC, AlexNDRmac commented
cc @dreamsxin Now you can see what I meant when told about fix in `Library/Compiler.php`
There is Test with Expected result, so we can use it as target point.

2019-02-19 07:25 UTC, dreamsxin commented
This config 
```json
    "globals": {
        "test.my_setting_1": {
            "type": "bool",
            "default": false
        },
    },
```
change to:
```json
    "globals": {
        "my_setting_1": {
            "type": "bool",
            "default": false
        },
    },
```
will generate `test.my_setting_1`.

2019-02-19 10:56 UTC, sergeyklay requested changes

2019-02-19 10:56 UTC, sergeyklay commented on Library/Code/Builder/Struct.php
> +     * @see https://docs.zephir-lang.com/en/0.10/globals
```suggestion
     * @see https://docs.zephir-lang.com/latest/en/globals
```

2019-02-19 10:56 UTC, sergeyklay commented on Library/Code/Builder/Struct.php
> +        //$iniName = $structName;
```suggestion
```

2019-02-19 10:56 UTC, sergeyklay commented on config.json
> +    "description": "<b>Zephir</b> - is a high level <strong>Programming Language</strong> that eases the creation and maintainability of extensions for PHP.",
```suggestion
    "description": "Description test for<br\/>Test Extension",
```

2019-02-19 10:56 UTC, sergeyklay commented on config.json
> +    "description": "<b>Zephir</b> - is a high level <strong>Programming Language</strong> that eases the creation and maintainability of extensions for PHP.",
It is not Zephir. It is test extension

2019-02-19 10:56 UTC, sergeyklay commented on ext/php_test.h
> +#define PHP_TEST_DESCRIPTION "<b>Zephir</b> - is a high level <strong>Programming Language</strong> that eases the creation and maintainability of extensions for PHP."
```suggestion#define PHP_TEST_DESCRIPTION "Description test for<br/>Test Extension"
```

It is not Zephir. It is test extension

2019-02-19 10:56 UTC, sergeyklay commented on ext/php_test.h
> +#define PHP_TEST_NAME        "Zephir Test Extension"
```suggestion
#define PHP_TEST_NAME        "Test Extension"
```

2019-02-19 10:56 UTC, sergeyklay commented on config.json
> +    "name": "Zephir Test Extension",
```suggestion
    "name": "Test Extension",
```

2019-02-19 12:38 UTC, AlexNDRmac commented on config.json
> +    "name": "Zephir Test Extension",
Everything fixed

2019-02-19 12:41 UTC, AlexNDRmac commented
@dreamsxin you were right :)  I did't do the tests correctly. Thank you for your participation.

2019-02-19 15:37 UTC, sergeyklay approved these changes

2019-02-19 15:37 UTC, merged

2019-02-19 15:38 UTC, sergeyklay commented
Thank you