#1103 - Added support syntax assign-bitwise operators
zephir-lang/zephir pull request #2215
Opened 2021-04-14 10:19 UTC by JellyBrick

Hello!

* Type: new feature
* Link to issue:

In raising this pull request, I confirm the following:

- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I updated the CHANGELOG

Small description of the change:

See #1103

Thanks

2021-04-19 13:20 UTC, Jeckerson requested changes

2021-04-19 13:20 UTC, Jeckerson commented on Library/Statements/LetStatement.php
> +                 * @Todo: Replace on supported native bitwise-assignment
```suggestion
                 * TODO: Replace on supported native bitwise-assignment
```

2021-04-19 13:20 UTC, Jeckerson commented on Library/Statements/LetStatement.php
> +     * @return mixed
```suggestion
     * @return array
```

2021-04-19 13:20 UTC, Jeckerson commented on Library/Statements/LetStatement.php
> +     * @param $assignment
```suggestion
     * @param array $assignment
```

2021-04-19 13:20 UTC, Jeckerson commented on Library/Statements/LetStatement.php
> +    protected function replaceAssignBitwiseOnDirect($assignment)
```suggestion
    protected function replaceAssignBitwiseOnDirect(array $assignment): array
```

2021-04-19 13:20 UTC, Jeckerson commented on Library/Statements/LetStatement.php
> +        if ($assignment['assign-type'] != 'variable') {
```suggestion
        if ($assignment['assign-type'] !== 'variable') {
```

2021-04-19 18:41 UTC, Jeckerson approved these changes

2021-04-21 07:32 UTC, AlexNDRmac approved these changes

2021-04-21 07:44 UTC, merged